{easy
	{balancingFactorBonus {cp 1.00} {mp 1.00} {payback 1} }
	{chargeFactors
		{value "*=0.5"}
	}
}
{normal
	{balancingFactorBonus {cp 1.00} {mp 1.00} {payback 2} }
	{chargeFactors
		{value "*=0.6"}
	}
}
{hard
	{balancingFactorBonus {cp 1.00} {mp 1.10} {payback 3} }
	{chargeFactors
		{value "*=0.8"}
	}
}
{heroic
	{balancingFactorBonus {cp 1.00} {mp 1.20} {payback 4} }
	{chargeFactors
		{value "*=0.9"}
	}
}