	
	{"bot_marker"			("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(rus) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	
	{"bot_marker(ams)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(ams) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(ars)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(ars) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(bas)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(bas) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(bls)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(bls) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(bps)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(bps) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(das)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(das) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(ecs)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(ecs) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(dgs)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(dgs) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(eld)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(eld) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(ets)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(ets) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(ifs)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(ifs) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(igs)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(igs) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(kgs)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(kgs) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(tau)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(tau) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(tyr)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(tyr) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(ums)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(ums) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(ork)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(ork) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	
	{"bot_marker(rep)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(rep) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(cis)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(cis) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(reb)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(reb) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(emp)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(imp) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	
	{"bot_marker(rus)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(rus) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(ger)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(ger) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(ger2)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(ger2) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(eng)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(eng) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(usa)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(usa) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(jap)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(jap) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	
	{"bot_marker(lbd)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(lbd) g(non) b(non)) {cost 0} {score 0} {fore 1}}
	{"bot_marker(cmb)"		("v_1_i_0" c(0) c1(bot_marker) 	cp(0)	t(all) s(cmb) g(non) b(non)) {cost 0} {score 0} {fore 1}}	

	{"dron_kbg"		("v_1_i_0" c(0) c1(dron_kbg) t(all non) s(das) g(non) cp(0) cw(0) b(non)) {cost 0} {fore 1}}
	{"dron_kgl"		("v_1_i_0" c(0) c1(dron_kgl) t(all non) s(das) g(non) cp(0) cw(0) b(non)) {cost 0} {fore 1}}
	{"dron_kml"		("v_1_i_0" c(0) c1(dron_kml) t(all non) s(das) g(non) cp(0) cw(0) b(non)) {cost 0} {fore 1}}
	{"dron_kpg"		("v_1_i_0" c(0) c1(dron_kpg) t(all non) s(das) g(non) cp(0) cw(0) b(non)) {cost 0} {fore 1}}
	{"dron_ws_hb"		("v_1_i_0" c(0) c1(dron_ws_hb) t(all non) s(das) g(non) cp(0) cw(0) b(non)) {cost 0} {fore 1}}
	{"dron_ws_lc"		("v_1_i_0" c(0) c1(dron_ws_lc) t(all non) s(das) g(non) cp(0) cw(0) b(non)) {cost 0} {fore 1}}
	{"dron_ws_lc_red"		("v_1_i_0" c(0) c1(dron_ws_lc_red) t(all non) s(das) g(non) cp(0) cw(0) b(non)) {cost 0} {fore 1}}
	{"dron_tau_fb"		("v_1_i_0" c(0) c1(dron_tau_fb) t(all non) s(tau) g(non) cp(0) cw(0) b(non)) {cost 0} {fore 1}}
	
	{"hunter_missile"		("v_1_i_0" c(0) c1(dron_tau_fb) t(all non) s(das) g(non) cp(0) cw(0) b(non)) {cost 0} {fore 1}}
	{"airburst_shell"			("v_1_i_0" c(0) c1(dron_tau_fb) t(all non) s(tau) g(non) cp(0) cw(0) b(non)) {cost 0} {fore 1}}
	{"airburst_shell_kiker"		("v_1_i_0" c(0) c1(dron_tau_fb) t(all non) s(tau) g(non) cp(0) cw(0) b(non)) {cost 0} {fore 1}}
	{"smart_missile"		("v_1_i_0" c(0) c1(dron_tau_fb) t(all non) s(tau) g(non) cp(0) cw(0) b(non)) {cost 0} {fore 1}}