			{"Human"
				{title "mp/alliance/human"}
				{armies "igs"}
				{armies "ams"}
				{armies "kgs"}
				{armies "ars"}
				{armies "ets"}
				{armies "das"}
				{armies "ifs"}
				{armies "ums"}
				{armies "bas"}
				{icon "/interface/pages/multi/flag_imp"}
			}
			{"Chaos"
				{title "mp/alliance/chaos"}
				{armies "bls"}
				{armies "bps"}
				{armies "dgs"}
				{icon "/interface/pages/multi/flag_chaos"}
			}
			{"Ksenos"
				{title "mp/alliance/ksenos"}
				{armies "tau"}
				{armies "eld"}
				{icon "/interface/pages/multi/flag_ksenos"}
			}